"""empty message

Revision ID: 8afd446e8218
Revises: b3d7fd041368
Create Date: 2019-08-18 13:47:05.917463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afd446e8218'
down_revision = 'b3d7fd041368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'in_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'out_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'out_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'in_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
