-- MySQL Script generated by MySQL Workbench
-- Mon Aug 19 20:01:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema equip-trak
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema equip-trak
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `equip-trak` DEFAULT CHARACTER SET utf8 ;
USE `equip-trak` ;

-- -----------------------------------------------------
-- Table `equip-trak`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equip-trak`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `user_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `created_on` DATETIME NULL,
  `updated_on` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equip-trak`.`equipments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equip-trak`.`equipments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `equip_id` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NULL,
  `manufacturer` VARCHAR(45) NULL,
  `serial` VARCHAR(45) NULL,
  `created_on` DATETIME NULL,
  `updated_on` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equip-trak`.`conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equip-trak`.`conditions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `condition` VARCHAR(45) NULL,
  `created_on` DATETIME NULL,
  `updated_on` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equip-trak`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equip-trak`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  `created_on` DATETIME NULL,
  `updated_on` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equip-trak`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equip-trak`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `equipments_id` INT NOT NULL,
  `checkout_user_id` INT NOT NULL,
  `checkout_condition_id` INT NOT NULL,
  `checkout_comment` VARCHAR(255) NULL,
  `checkout_time` DATETIME NULL,
  `checkout_location` VARCHAR(45) NULL,
  `checkin_user_id` INT NULL,
  `checkin_condition_id` INT NULL,
  `checkin_comment` VARCHAR(255) NULL,
  `checkin_time` DATETIME NULL,
  `checkin_location` VARCHAR(255) NULL,
  `created_on` DATETIME NULL,
  `updated_on` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_users_idx` (`checkout_user_id` ASC) VISIBLE,
  INDEX `fk_transactions_equipments1_idx` (`equipments_id` ASC) VISIBLE,
  INDEX `fk_transactions_conditions1_idx` (`checkout_condition_id` ASC) VISIBLE,
  INDEX `fk_transactions_users1_idx` (`checkin_user_id` ASC) VISIBLE,
  INDEX `fk_transactions_conditions2_idx` (`checkin_condition_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_users`
    FOREIGN KEY (`checkout_user_id`)
    REFERENCES `equip-trak`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_equipments1`
    FOREIGN KEY (`equipments_id`)
    REFERENCES `equip-trak`.`equipments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_conditions1`
    FOREIGN KEY (`checkout_condition_id`)
    REFERENCES `equip-trak`.`conditions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_users1`
    FOREIGN KEY (`checkin_user_id`)
    REFERENCES `equip-trak`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_conditions2`
    FOREIGN KEY (`checkin_condition_id`)
    REFERENCES `equip-trak`.`conditions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equip-trak`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equip-trak`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admins_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_admins_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `equip-trak`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
